### PR TITLE
Added react vite + react-query example

### PR DESCRIPTION
**Pull request by paul-sachs**

### CODE REVIEW

**Comment by akshayjshah** [comment]
Wait, are we not planning to include a react-query example?

**Comment by timostamm** [comment]
We are actually planning a more direct integration with React Query that gives you a ReactQueryClient - similar to the [PromiseClient and CallbackClient](https://connect.build/docs/web/using-clients) we already provide. 

This was only closed because it is not ready yet, but it will resurface soon.

**Comment by paul-sachs** [comment]
Yep, I just want it to bake a little internally before putting out examples using it. The plan is to actually use it within the BSR/Studio. Gonna dogfood it.

**Comment by akshayjshah** [comment]
Awesome!

**Pull request closed without merging**
